export const dummy = {
  dates: {
    maximum: "2024-01-31",
    minimum: "2023-12-20",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
      genre_ids: [28, 12, 14],
      id: 572802,
      original_language: "en",
      original_title: "Aquaman and the Lost Kingdom",
      overview:
        "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
      popularity: 4197.714,
      poster_path: "/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
      release_date: "2023-12-22",
      title: "Aquaman and the Lost Kingdom",
      video: false,
      vote_average: 6.856,
      vote_count: 837,
    },
    {
      adult: false,
      backdrop_path: "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
      genre_ids: [16, 12, 35, 10751, 28],
      id: 940551,
      original_language: "en",
      original_title: "Migration",
      overview:
        "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
      popularity: 1655.989,
      poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
      release_date: "2023-12-22",
      title: "Migration",
      video: false,
      vote_average: 7.822,
      vote_count: 219,
    },
    {
      adult: false,
      backdrop_path: "/vdpE5pjJVql5aD6pnzRqlFmgxXf.jpg",
      genre_ids: [18, 36],
      id: 906126,
      original_language: "es",
      original_title: "La sociedad de la nieve",
      overview:
        "On October 13, 1972, Uruguayan Air Force Flight 571, chartered to take a rugby team to Chile, crashes into a glacier in the heart of the Andes.",
      popularity: 863.788,
      poster_path: "/2e853FDVSIso600RqAMunPxiZjq.jpg",
      release_date: "2023-12-22",
      title: "Society of the Snow",
      video: false,
      vote_average: 8.07,
      vote_count: 1345,
    },
    {
      adult: false,
      backdrop_path: "/6OnoMgGFuZ921eV8v8yEyXoag19.jpg",
      genre_ids: [28, 53],
      id: 1211957,
      original_language: "en",
      original_title: "The Painter",
      overview:
        "An ex-CIA operative is thrown back into a dangerous world when a mysterious woman from his past resurfaces. Now exposed and targeted by a relentless killer and a rogue black ops program, he must rely on skills he thought he left behind in a high-stakes game of survival.",
      popularity: 630.616,
      poster_path: "/UZ0ydgbXtnrq8xZCI5lHVXVcH9.jpg",
      release_date: "2024-01-05",
      title: "The Painter",
      video: false,
      vote_average: 5.868,
      vote_count: 19,
    },
    {
      adult: false,
      backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
      genre_ids: [18, 36],
      id: 872585,
      original_language: "en",
      original_title: "Oppenheimer",
      overview:
        "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
      popularity: 536.381,
      poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      release_date: "2024-01-12",
      title: "Oppenheimer",
      video: false,
      vote_average: 8.117,
      vote_count: 6342,
    },
    {
      adult: false,
      backdrop_path: "/h0oBqUpax591vOacpBsDJ8cynjk.jpg",
      genre_ids: [878, 10749, 35],
      id: 792307,
      original_language: "en",
      original_title: "Poor Things",
      overview:
        "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
      popularity: 530.655,
      poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
      release_date: "2023-12-08",
      title: "Poor Things",
      video: false,
      vote_average: 8.134,
      vote_count: 340,
    },
    {
      adult: false,
      backdrop_path: "/kWyQh9fCrgcMfhqZmqtp89Q0TrT.jpg",
      genre_ids: [35, 10749],
      id: 1072790,
      original_language: "en",
      original_title: "Anyone But You",
      overview:
        "After an amazing first date, Bea and Ben¡¯s fiery attraction turns ice cold ? until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
      popularity: 427.938,
      poster_path: "/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg",
      release_date: "2023-12-22",
      title: "Anyone But You",
      video: false,
      vote_average: 7.225,
      vote_count: 109,
    },
    {
      adult: false,
      backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
      genre_ids: [28, 53],
      id: 866398,
      original_language: "en",
      original_title: "The Beekeeper",
      overview:
        "One man¡¯s campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
      popularity: 403.52,
      poster_path: "/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
      release_date: "2024-01-12",
      title: "The Beekeeper",
      video: false,
      vote_average: 7.4,
      vote_count: 176,
    },
    {
      adult: false,
      backdrop_path: "/klb3yODwKMRle19EcvdeSatEZL7.jpg",
      genre_ids: [27, 53],
      id: 1072342,
      original_language: "en",
      original_title: "Night Swim",
      overview:
        "Forced into early retirement by a degenerative illness, former baseball player Ray Waller moves into a new house with his wife and two children. He hopes that the backyard swimming pool will be fun for the kids and provide physical therapy for himself. However, a dark secret from the home's past soon unleashes a malevolent force that drags the family into the depths of inescapable terror.",
      popularity: 395.711,
      poster_path: "/gSkfBGdxdialBMM7P02V4hcI6Ij.jpg",
      release_date: "2024-01-05",
      title: "Night Swim",
      video: false,
      vote_average: 5.741,
      vote_count: 110,
    },
    {
      adult: false,
      backdrop_path: "/47SVqaO02doJ06tOmrjiWDkwU3T.jpg",
      genre_ids: [28, 53],
      id: 927107,
      original_language: "en",
      original_title: "The Bricklayer",
      overview:
        "Someone is blackmailing the CIA by assassinating foreign journalists and making it look like the agency is responsible. As the world begins to unite against the U.S., the CIA must lure its most brilliant ? and rebellious ? operative out of retirement, forcing him to confront his checkered past while unraveling an international conspiracy.",
      popularity: 344.154,
      poster_path: "/pwOQ9lqLX1OgsJRSybS662wMcu8.jpg",
      release_date: "2024-01-05",
      title: "The Bricklayer",
      video: false,
      vote_average: 6.3,
      vote_count: 65,
    },
    {
      adult: false,
      backdrop_path: "/bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg",
      genre_ids: [878, 27, 28],
      id: 940721,
      original_language: "ja",
      original_title: "«´«¸«é-1.0",
      overview:
        "In postwar Japan, a new terror rises. Will the devastated people be able to survive... let alone fight back?",
      popularity: 325.492,
      poster_path: "/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
      release_date: "2023-12-01",
      title: "Godzilla Minus One",
      video: false,
      vote_average: 7.922,
      vote_count: 353,
    },
    {
      adult: false,
      backdrop_path: "/9uNCYl2qmg16FLarg3n3Ea0PBIG.jpg",
      genre_ids: [27, 53],
      id: 1216784,
      original_language: "en",
      original_title: "Sunrise",
      overview:
        "When an ex-cop named Fallon returns to the scene of a horrific crime, the residents of a rural town soon discover that this dark visitor is really a vampire who feeds on blood and fear. After he is befriended by a kind immigrant family, the instinctive killer is faced with a choice between revenge and redemption.",
      popularity: 387.653,
      poster_path: "/4aRvg2ybz646gciX5M6qaclunC2.jpg",
      release_date: "2024-01-19",
      title: "Sunrise",
      video: false,
      vote_average: 4,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
      genre_ids: [16, 28, 12, 878],
      id: 569094,
      original_language: "en",
      original_title: "Spider-Man: Across the Spider-Verse",
      overview:
        "After reuniting with Gwen Stacy, Brooklyn¡¯s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse¡¯s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
      popularity: 249.874,
      poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
      release_date: "2024-01-19",
      title: "Spider-Man: Across the Spider-Verse",
      video: false,
      vote_average: 8.372,
      vote_count: 5610,
    },
    {
      adult: false,
      backdrop_path: "/4W11akSpZBp8O09cQFEO0lqmVJl.jpg",
      genre_ids: [18, 36],
      id: 365620,
      original_language: "en",
      original_title: "Ferrari",
      overview:
        "Set during the summer of 1957. Ex-racecar driver, Enzo Ferrari, is in crisis. Bankruptcy stalks the company he and his wife, Laura, built from nothing ten years earlier. Their tempestuous marriage struggles with the mourning for one son and the acknowledgement of another.",
      popularity: 190.604,
      poster_path: "/xBFyJHvXCTgf9Vmq5uCnXRHrMQ4.jpg",
      release_date: "2023-12-25",
      title: "Ferrari",
      video: false,
      vote_average: 6.771,
      vote_count: 229,
    },
    {
      adult: false,
      backdrop_path: "/mpIpHN7DJprENGiSvxOaG5mLzht.jpg",
      genre_ids: [35],
      id: 673593,
      original_language: "en",
      original_title: "Mean Girls",
      overview:
        "New student Cady Heron is welcomed into the top of the social food chain by the elite group of popular girls called ¡®The Plastics,¡¯ ruled by the conniving queen bee Regina George and her minions Gretchen and Karen. However, when Cady makes the major misstep of falling for Regina¡¯s ex-boyfriend Aaron Samuels, she finds herself prey in Regina¡¯s crosshairs. As Cady sets to take down the group¡¯s apex predator with the help of her outcast friends Janis and Damian, she must learn how to stay true to herself while navigating the most cutthroat jungle of all: high school.",
      popularity: 172.369,
      poster_path: "/fbbj3viSUDEGT1fFFMNpHP1iUjw.jpg",
      release_date: "2024-01-12",
      title: "Mean Girls",
      video: false,
      vote_average: 6.611,
      vote_count: 95,
    },
    {
      adult: false,
      backdrop_path: "/X8yF6STUk5Zr5nAuLBJiio8Sxh.jpg",
      genre_ids: [18, 10749, 878],
      id: 1143183,
      original_language: "tl",
      original_title: "Rewind",
      overview:
        "Mary loves John for as long as she can remember. But after years of marriage, John's priorities shift, leading to a strained relationship with Mary, which causes a tragic accident that takes away Mary's life. Until one day, John gets an extraordinary proposition - to rewind time and save the life of the woman he loves.",
      popularity: 116.267,
      poster_path: "/i8UjdAwezeFHHR4opNb3LxDCQWC.jpg",
      release_date: "2024-01-05",
      title: "Rewind",
      video: false,
      vote_average: 6.762,
      vote_count: 21,
    },
    {
      adult: false,
      backdrop_path: "/bq9FpkTw9I3s1cSRuZxQibM2xOx.jpg",
      genre_ids: [18, 36, 10752],
      id: 467244,
      original_language: "en",
      original_title: "The Zone of Interest",
      overview:
        "The commandant of Auschwitz, Rudolf H?ss, and his wife Hedwig, strive to build a dream life for their family in a house and garden next to the camp.",
      popularity: 97.49,
      poster_path: "/ruyeAfmxbNPWZ92dWymqwTc6nWV.jpg",
      release_date: "2023-12-15",
      title: "The Zone of Interest",
      video: false,
      vote_average: 7.4,
      vote_count: 28,
    },
    {
      adult: false,
      backdrop_path: "/iP3fL9jwcYeGMyfZKAT6KqW1qc.jpg",
      genre_ids: [18],
      id: 558915,
      original_language: "en",
      original_title: "The Color Purple",
      overview:
        "A decades-spanning tale of love and resilience and of one woman's journey to independence. Celie faces many hardships in her life, but ultimately finds extraordinary strength and hope in the unbreakable bonds of sisterhood.",
      popularity: 101.264,
      poster_path: "/3Jc93sCl0DqkePYjw47zHpqj7YS.jpg",
      release_date: "2023-12-25",
      title: "The Color Purple",
      video: false,
      vote_average: 6.706,
      vote_count: 64,
    },
    {
      adult: false,
      backdrop_path: "/mHpoCdCSebNDIIHbqaAxbD57o7H.jpg",
      genre_ids: [18, 36],
      id: 823452,
      original_language: "en",
      original_title: "The Boys in the Boat",
      overview:
        "The triumphant underdog story of the University of Washington men's rowing team, who stunned the world by winning gold at the 1936 Berlin Olympics.",
      popularity: 75.314,
      poster_path: "/eNOyS9hmdBoP5zpowbU4Kfh1JYB.jpg",
      release_date: "2023-12-25",
      title: "The Boys in the Boat",
      video: false,
      vote_average: 7.851,
      vote_count: 57,
    },
    {
      adult: false,
      backdrop_path: "/rQaHA74pevnGsxcKGaoZVGWe9TC.jpg",
      genre_ids: [16, 10751, 35, 14],
      id: 508442,
      original_language: "en",
      original_title: "Soul",
      overview:
        "Joe Gardner is a middle school teacher with a love for jazz music. After a successful audition at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.",
      popularity: 72.46,
      poster_path: "/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",
      release_date: "2024-01-12",
      title: "Soul",
      video: false,
      vote_average: 8.14,
      vote_count: 9796,
    },
  ],
  total_pages: 10,
  total_results: 184,
};
